export const logo = require('./logo.svg');
export const off = require('./off.svg'); //eye
export const harry = require('./harry.svg');
export const book = require('./book.svg');
export const heart = require('./heart.svg');
export const holy = require('./holy.svg');
export const home = require('./home.svg');
export const jssmall = require('./js-small.svg');
export const learn = require('./learn-UX.svg');
export const poly = require('./poly.svg');
export const qr = require('./qr.svg');
export const react = require('./react.svg');
export const rich = require('./rich.svg');
export const search = require('./search.svg');
export const sp = require('./sp.svg');
export const sprint = require('./sprint.svg');
export const sub = require('./sub.svg');
export const things = require('./things.svg');
export const think = require('./think.svg');
export const tick = require('./tick.svg');
export const trac = require('./trac.svg');
export const me = require('./me.jpg'); //heart complete
export const pp = require('./pp.svg');
